// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using okulSistem.DataAccess;

#nullable disable

namespace okulSistem.DataAccess.Migrations
{
    [DbContext(typeof(OkulSistemDbContext))]
    [Migration("20220620135037_update")]
    partial class update
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("okulSistem.Entities.Ders", b =>
                {
                    b.Property<int>("dersId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("dersId"), 1L, 1);

                    b.Property<string>("dersAciklama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("dersAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("dersDurum")
                        .HasColumnType("bit");

                    b.Property<int?>("ogrenciId")
                        .HasColumnType("int");

                    b.HasKey("dersId");

                    b.HasIndex("ogrenciId");

                    b.ToTable("Dersler");
                });

            modelBuilder.Entity("okulSistem.Entities.Ogrenci", b =>
                {
                    b.Property<int>("ogrenciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ogrenciId"), 1L, 1);

                    b.Property<string>("ogrenciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ogreniciDurum")
                        .HasColumnType("bit");

                    b.Property<string>("ogreniciNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ogreniciSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ogrenciId");

                    b.ToTable("Ogrenciler");
                });

            modelBuilder.Entity("okulSistem.Entities.Ogretmen", b =>
                {
                    b.Property<int>("ogretmenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ogretmenId"), 1L, 1);

                    b.Property<string>("ogretmenAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ogretmenDers")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("ogretmenDurum")
                        .HasColumnType("bit");

                    b.Property<string>("ogretmenSoyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ogretmenId");

                    b.ToTable("Ogretmenler");
                });

            modelBuilder.Entity("okulSistem.Entities.Ders", b =>
                {
                    b.HasOne("okulSistem.Entities.Ogrenci", null)
                        .WithMany("ogreniDersler")
                        .HasForeignKey("ogrenciId");
                });

            modelBuilder.Entity("okulSistem.Entities.Ogrenci", b =>
                {
                    b.Navigation("ogreniDersler");
                });
#pragma warning restore 612, 618
        }
    }
}
